### ISSUE TITLE
Feature Request - enable configuration of portable/stationary dynamic model

### ISSUE THREAD

**Issue by CaptainMidnight** [SlightlyLoony/gpsctl#1]
Hi I understand this code was last updated 3yrs ago, but is it possible for your version of gpsctl to be able to configure gps portable/stationary dynamic model please?

Reading the gps configuration via your tool, portable model is configured, can your tool change this to stationary model?

**Comment by SlightlyLoony** [comment]
Hello, Captain Midnight!

I'm afraid I no longer have a test setup for this, plus I have completely
forgotten how it works!  :)  The whole reason I open-sourced it was so that
other people could maintain it...

Tom...

**Comment by CaptainMidnight** [comment]
Hahahaha, no problem at all, your programme seemed an easier option than trying to figure out how to find and install a pi version of the ubxtool.

Thanks again for the quick reply.
